name: Ardour Cross Compile Build for Windows

on:
  push:
    branches: 
      - win
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches: 
      - win
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  repository_dispatch:
    types: ardour-win-build
  workflow_dispatch:

env:
  ARDOUR_VERSION: 6.9
  # available upload services: wetransfer.com, file.io, 0x0.st
  UPLOAD_SERVICE: wetransfer.com
  # ardour spurce code tar ball, need check its sha256sums.
  # https://community.ardour.org/srctar
  # https://fossies.org/linux/misc/Ardour-6.8.0.tar.bz2

jobs:
  ardour-x-win-build:
    name: Ardour X-Build for Win ${{ matrix.config.arch }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              arch: x86_64,
              warch: w64,
              image_repo: debian,
              image_tag: buster
            }
          - {
              arch: i686,
              warch: w32,
              image_repo: debian,
              image_tag: buster
            }
    container:
      image: ${{ matrix.config.image_repo }}:${{ matrix.config.image_tag }}
      options: -v ${{ github.workspace }}:/home/ardour:rw
    steps:

      - name: Install Dependencies on Debian
        shell: bash
        run: |
          apt-get -y -qq update && apt-get -y --no-install-recommends install \
            apt-transport-https \
            curl \
            wget \
            sudo \
            git \
            ca-certificates \
            unzip \
            rsync \
            ed \
            yasm \
            cmake \
            nsis \
            subversion \
            ocaml-nox \
            gperf \
            meson \
            python \
            python3 \
            python3-pip \
            build-essential \
            ccache \
            autoconf \
            automake \
            libtool \
            pkg-config

      # - name: Checkout Build Tools
      #   shell: bash
      #   run: |
      #     cd ${{ github.workspace }}
      #     git clone --branch x-win https://github.com/ZetaoYang/ardour-build.git .

      - name: Checkout Build Tools
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          fetch-depth: 0
          ref: win
          path: '.'

      # - name: Get Ardour Latest Release Source Code
      #   shell: bash
      #   run: |
      #     ls -l ${{ github.workspace }}
      #     git clone --depth 1 --branch ${{ env.ARDOUR_VERSION }} https://github.com/Ardour/ardour.git ${{ github.workspace }}/src

      - name: Get Ardour Latest Release Source Code
        uses: actions/checkout@v2
        with:
          repository: 'Ardour/ardour'
          fetch-depth: 1
          ref: ${{ env.ARDOUR_VERSION }}
          path: './src'

      - name: Prepare Directory
        shell: bash
        run: |
          mkdir -p ${{ github.workspace }}/tmp/winsrc

      # created a windows32/64bit build-stack for Ardour 
      # cross-compiled on GNU/Linux using gcc-8.2 (debian buster)
      - name: Install Build Stack Env
        shell: bash
        run: |
          bash /home/ardour/ci/x-mingw.sh
        env:
          XARCH: ${{ matrix.config.arch }}
          SRCDIR: /home/ardour/tmp/winsrc
          TMPDIR: /home/ardour/tmp
          ROOT: /home/ardour

      - name: Compile
        shell: bash
        run: |
          bash /home/ardour/ci/compile.sh
        env:
          XARCH: ${{ matrix.config.arch }}
          ROOT: /home/ardour

      - name: Package
        shell: bash
        run: |
          bash /home/ardour/src/tools/x-win/package.sh
        env:
          XARCH: ${{ matrix.config.arch }}
          ROOT: /home/ardour
          TMPDIR: /home/ardour/tmp
          SRCCACHE: /home/ardour/tmp/winsrc

      - name: Upload Binary
        # /home/ardour/tmp/Ardour-6.8.0-w64-Setup.exe
        shell: bash
        run: |
          TEMP_DOWNLOAD_URL=$(sh /home/ardour/ci/services/${{ env.UPLOAD_SERVICE }}.sh /home/ardour/tmp/Ardour-*-${{ matrix.config.warch }}-Setup.exe)
          echo Download URL is $TEMP_DOWNLOAD_URL

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Ardour-Cross-Compile-Win-Artifact
          path: |
            ${{ github.workspace }}/tmp/Ardour-*-${{ matrix.config.warch }}-Setup.exe
